FROM maven:3-eclipse-temurin-25-alpine AS build
WORKDIR /app

COPY pom.xml ./
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:25-jre-alpine AS run
WORKDIR /app

COPY --from=build /app/target/*.jar ./app.jar
EXPOSE 8000

ENTRYPOINT ["java", "-jar", "app.jar"]
